matrix:
  include:
    - language: java
      java:
        - os: windows
        - jdk: oraclejdk11
      before_install:
        - chmod +x gradle
      install:
        - ./gradlew assemble
      script:
        - ./gradlew stage

    - language: java
      java:
        - os: windows
        - jdk: oraclejdk10
      before_install:
        - chmod +x gradle
      install:
        - ./gradlew assemble
      script:
        - ./gradlew stage
